/*
 * Adapted from the Wizardry License
 *
 * Copyright (c) 2017 Team Pepsi
 *
 * Permission is hereby granted to any persons and/or organizations using this software to copy, modify, merge, publish, and distribute it.
 * Said persons and/or organizations are not allowed to use the software or any derivatives of the work for commercial use or any other means to generate income, nor are they allowed to claim this software as their own.
 *
 * The persons and/or organizations are also disallowed from sub-licensing and/or trademarking this software without explicit permission from Team Pepsi.
 *
 * Any persons and/or organizations using this software must disclose their source code and have it publicly available, include this license, provide sufficient credit to the original authors of the project (IE: Team Pepsi), as well as provide a link to the original project.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package net.daporkchop.pepsimod.wdl;

import com.google.common.collect.Sets;
import net.daporkchop.pepsimod.wdl.api.IEntityManager;
import net.daporkchop.pepsimod.wdl.api.IWDLMod;
import net.daporkchop.pepsimod.wdl.api.IWDLModDescripted;
import net.minecraft.entity.Entity;
import net.minecraft.entity.item.EntityArmorStand;

import java.util.Set;

/**
 * Handles holograms.
 * <br/>
 * Right now, the definition of a hologram is an invisible ArmorStand
 * with a custom name set.  This is how holograms are generated by the
 * <a href="http://dev.bukkit.org/bukkit-plugins/holographic-displays/">
 * Holographic Displays</a> plugin, which is the most popular version.
 * However, the older style of holograms created by Asdjke's method
 * <a href="https://www.youtube.com/watch?v=q1B19JvX5TE">(showcased in
 * this video)</a> do not get recognized.  I don't think this is a big
 * problem, but it is something to keep in mind.
 * <br/>
 * This is also an example of how a {@link IWDLMod} would be implemented.
 */
public class HologramHandler implements IEntityManager,
        IWDLModDescripted {

    @Override
    public boolean isValidEnvironment(String version) {
        return true;
    }

    @Override
    public String getEnvironmentErrorMessage(String version) {
        return null;
    }

    @Override
    public String getDisplayName() {
        return "Hologram support";
    }

    @Override
    public Set<String> getProvidedEntities() {
        return Sets.newHashSet("x-extended:hologram");
    }

    @Override
    public String getIdentifierFor(Entity entity) {
        if (entity instanceof EntityArmorStand &&
                entity.isInvisible() &&
                entity.hasCustomName()) {
            return "x-extended:hologram";
        }

        return null;
    }

    @Override
    public int getTrackDistance(String identifier, Entity entity) {
        // Assume holograms act the same as armor stands
        if (identifier == "x-extended:hologram") {
            return EntityUtils.getEntityTrackDistance("default", "minecraft:armor_stand", entity);
        } else {
            return -1;
        }
    }

    @Override
    public boolean enabledByDefault(String identifier) {
        return true;
    }

    @Override
    public String getGroup(String identifier) {
        return "Other";
    }

    @Override
    public String getDisplayGroup(String group) {
        // TODO
        return null;
    }

    @Override
    public String getDisplayIdentifier(String identifier) {
        // TODO
        return "Hologram";
    }

    @Override
    public String getMainAuthor() {
        return "Pokechu22";
    }

    @Override
    public String[] getAuthors() {
        return null;
    }

    @Override
    public String getURL() {
        return null;
    }

    @Override
    public String getDescription() {
        return "Provides basic support for disabling holograms.";
    }
}
